function hnd = DrawLights(lights_state, inter, hnd)

diam = 5;
from_center = inter.ur(1);
delete(hnd)

pos1 = [inter.center + [0 from_center] - diam/2*ones(1,2), diam, diam];
pos2 = [inter.center + [from_center 0] - diam/2*ones(1,2), diam, diam];
pos3 = [inter.center + [0 -from_center] - diam/2*ones(1,2), diam, diam];
pos4 = [inter.center + [-from_center 0] - diam/2*ones(1,2), diam, diam];

hnd = [rectangle('Position', pos1, 'Curvature', [1 1], ...
  'FaceColor', lights_state(1)), ...
rectangle('Position', pos2, 'Curvature', [1 1], ...
  'FaceColor', lights_state(2)), ...
rectangle('Position', pos3, 'Curvature', [1 1], ...
  'FaceColor', lights_state(3)), ...
rectangle('Position', pos4, 'Curvature', [1 1], ...
  'FaceColor', lights_state(4))];

end