function hnd = DrawLights(lights_state, int, hnd)

diam = 5;
from_center = int.ur(1);
delete(hnd)

pos1 = [int.center + [0 from_center] - diam/2*ones(1,2), diam, diam];
pos2 = [int.center + [from_center 0] - diam/2*ones(1,2), diam, diam];
pos3 = [int.center + [0 -from_center] - diam/2*ones(1,2), diam, diam];
pos4 = [int.center + [-from_center 0] - diam/2*ones(1,2), diam, diam];

hnd = [rectangle('Position', pos1, 'Curvature', [1 1], ...
  'FaceColor', lights_state(1)), ...
rectangle('Position', pos2, 'Curvature', [1 1], ...
  'FaceColor', lights_state(2)), ...
rectangle('Position', pos3, 'Curvature', [1 1], ...
  'FaceColor', lights_state(3)), ...
rectangle('Position', pos4, 'Curvature', [1 1], ...
  'FaceColor', lights_state(4))];

end